import cv2
import argparse
import numpy as np
import simple
import os

parser = argparse.ArgumentParser(description='Given set of test images, allows user to select correct angle, and correct phone')
parser.add_argument('tfolder', help='the folder of test images')
parser.add_argument('pfolder', help='the folder of phone images')
parser.add_argument('flabel', help='The text file of labels')

args = parser.parse_args()

#phones are as follows a5-b,a5-f,i8-b,i8-f,s8-b,s8-f
'''
read file of all test labels, and than load pictures one at a time

run simple algorithm over it to get results
try to match weights to each output so that correct label is selected most of the time

IE load file of y's, x's are the mvs generated by simple method, generate weights.
'''

pNames = os.listdir(args.pfolder)
phones = []
for p in pNames:
	temp  = cv2.imread(args.pfolder + '/' + p,0)
	phones.append(simple.get_rot(temp))

tNames = os.listdir(args.tfolder)

labels = np.loadtxt(args.flabel,delimiter=",")
xs = []

#generating x's
for t in tNames:
	temp = cv2.imread(args.tfolder + '/' + t,0)
	tests = simple.get_py(temp,3)
	mvs = []
	for p in phones:
		mv,mtmp,mtest,mloc = simple.get_score(p,tests)
		mvs.append(mv)
	x = np.array(mvs) #training weights
	x = x/np.sum(x)
	xs.append(x)

xs = np.array(xs)
np.savetxt('inputs.txt',xs)